[package]
name = "stammw-blog"
version = "0.1.0"
authors = ["Jean-Christophe BEGUE <jc.begue@devisubox.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"

[dependencies.rocket_contrib]
version = "0.3.6"
default-features = false
features = ["handlebars_templates", "tera_templates"]
